// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR_fmAu8lupaAB4qKgzcDvhKh0FHhsdMg',
    appId: '1:867858324084:android:bab7d63fcea4e68108cf21',
    messagingSenderId: '867858324084',
    projectId: 'ayad-1c268',
    storageBucket: 'ayad-1c268.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2cyXJ3t9jM-ir86XVH-Q_C93bTZw9a6Y',
    appId: '1:867858324084:web:dbbe3cab6a6e3e1808cf21',
    messagingSenderId: '867858324084',
    projectId: 'ayad-1c268',
    authDomain: 'ayad-1c268.firebaseapp.com',
    storageBucket: 'ayad-1c268.appspot.com',
    measurementId: 'G-4R6TT037FT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDdQJGXcb9p-lhZiniPetqvQKeCxnx8Jk',
    appId: '1:867858324084:ios:6b471e7ad98b86c008cf21',
    messagingSenderId: '867858324084',
    projectId: 'ayad-1c268',
    storageBucket: 'ayad-1c268.appspot.com',
    iosBundleId: 'com.karimkhatib.ayad',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDdQJGXcb9p-lhZiniPetqvQKeCxnx8Jk',
    appId: '1:867858324084:ios:6b471e7ad98b86c008cf21',
    messagingSenderId: '867858324084',
    projectId: 'ayad-1c268',
    storageBucket: 'ayad-1c268.appspot.com',
    iosBundleId: 'com.karimkhatib.ayad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2cyXJ3t9jM-ir86XVH-Q_C93bTZw9a6Y',
    appId: '1:867858324084:web:9299e9dc0b05457d08cf21',
    messagingSenderId: '867858324084',
    projectId: 'ayad-1c268',
    authDomain: 'ayad-1c268.firebaseapp.com',
    storageBucket: 'ayad-1c268.appspot.com',
    measurementId: 'G-Q4KRVWMRBT',
  );

}