// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user.g.dart';
enum UserType{anon,admin,customer}
@freezed
class AppUser with _$AppUser {
  const factory AppUser({
    String? id,
    required String fullName,
    required String phone,
    required String username,
    required String password,
    required DateTime createdAt,
    required UserType type,
    String? token,

  }) = _User;

  factory AppUser.fromJson(Map<String, Object?> json)
      => _$AppUserFromJson(json);
}