

import 'package:ayad/users/domain/user.dart';
import 'package:equatable/equatable.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'auth_state.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'auth_state.g.dart';


enum AuthStatus { authorized, unAuthorized, initial }
@freezed
class AuthState with _$AuthState {

   factory AuthState({
    required AuthStatus authStatus,
     AppUser? currentUser
  })=_AuthState;

   factory AuthState.fromJson(Map<String, Object?> json)
      => _$AuthStateFromJson(json);
}
